/* ═══════════════════════════════════════════════════════════════════════
   store.js — the only module that knows where data comes from.

   Shape on disk (all static, generated by sp500_cache.py):
     data/index.json          one row per constituent, both snapshots
     data/summary.json        counts and failure reasons
     data/series/{TK}.json    EM history, per-day paths, daily OHLC bars

   The index loads once (~100 KB gzipped). Series load lazily on selection
   (~6 KB gzipped each) and are cached for the session, so revisiting a
   ticker is instant and a cold visit never pays for 498 of them.
   ═══════════════════════════════════════════════════════════════════════ */

const DATA = "./data";

const listeners = new Set();
const seriesCache = new Map();
const inflight = new Map();

export const state = {
  index: [],
  byTicker: new Map(),
  summary: null,
  selected: null,     // the row from index.json
  series: null,       // series for `selected`, or null while loading / absent
  seriesStatus: "idle", // idle | loading | ready | missing
};

/** subscribe to state changes; returns an unsubscribe function */
export function subscribe(fn) {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

function emit(reason) {
  for (const fn of listeners) fn(state, reason);
}

export async function load() {
  const [index, summary] = await Promise.all([
    fetch(`${DATA}/index.json`).then((r) => {
      if (!r.ok) throw new Error(`index.json → HTTP ${r.status}`);
      return r.json();
    }),
    fetch(`${DATA}/summary.json`).then((r) => (r.ok ? r.json() : null)),
  ]);

  state.index = index;
  state.summary = summary;
  state.byTicker = new Map(index.map((row) => [row.ticker, row]));
  emit("index");
  return state;
}

export const rated = () => state.index.filter((r) => Array.isArray(r.snaps));
export const unrateable = () => state.index.filter((r) => !Array.isArray(r.snaps));

/** the largest names by market value — a data-driven "common stocks" row */
export function largest(n = 12) {
  return rated()
    .slice()
    .sort((a, b) => (b.snaps[0].marketCap ?? 0) - (a.snaps[0].marketCap ?? 0))
    .slice(0, n);
}

/**
 * A peer set for the cross-sectional plates: same GICS sector, the names
 * closest in market value, always including the subject itself.
 *
 * Drawing all 498 constituents in a dumbbell chart is unreadable, and picking
 * the largest 12 index-wide would compare a utility against Apple. Sector plus
 * size is the comparison a credit reader actually wants.
 */
export function peers(row, n = 12) {
  if (!row?.snaps) return [];
  const cohort = rated().filter((r) => r.sector === row.sector);
  const size = row.snaps[0].marketCap ?? 0;
  const near = cohort
    .filter((r) => r.ticker !== row.ticker)
    .sort((a, b) => Math.abs((a.snaps[0].marketCap ?? 0) - size) - Math.abs((b.snaps[0].marketCap ?? 0) - size))
    .slice(0, n - 1);
  return [row, ...near];
}

/**
 * Free-text lookup over symbol and company name. Exact symbol wins, then
 * symbol prefix, then name substring — so typing "KO" never buries Coca-Cola
 * under "Kohl's" or any name containing "ko".
 */
export function search(query, limit = 8) {
  const q = String(query ?? "").trim().toUpperCase();
  if (!q) return [];
  const exact = [];
  const prefix = [];
  const inName = [];
  for (const row of state.index) {
    const tk = row.ticker.toUpperCase();
    if (tk === q) exact.push(row);
    else if (tk.startsWith(q)) prefix.push(row);
    else if (String(row.name ?? "").toUpperCase().includes(q)) inName.push(row);
  }
  return [...exact, ...prefix, ...inName].slice(0, limit);
}

export async function select(ticker) {
  const row = state.byTicker.get(String(ticker ?? "").trim().toUpperCase());
  if (!row) return null;

  state.selected = row;
  state.series = seriesCache.get(row.ticker) ?? null;
  state.seriesStatus = state.series ? "ready" : row.snaps ? "loading" : "missing";
  emit("selected");

  if (state.series || !row.snaps) return row;

  try {
    const series = await fetchSeries(row.ticker);
    seriesCache.set(row.ticker, series);
    // a later selection may have won the race — only publish if still current
    if (state.selected?.ticker === row.ticker) {
      state.series = series;
      state.seriesStatus = "ready";
      emit("series");
    }
  } catch {
    if (state.selected?.ticker === row.ticker) {
      state.series = null;
      state.seriesStatus = "missing";
      emit("series");
    }
  }
  return row;
}

function fetchSeries(ticker) {
  if (inflight.has(ticker)) return inflight.get(ticker);
  const p = fetch(`${DATA}/series/${encodeURIComponent(ticker)}.json`)
    .then((r) => {
      if (!r.ok) throw new Error(`series/${ticker} → HTTP ${r.status}`);
      return r.json();
    })
    .finally(() => inflight.delete(ticker));
  inflight.set(ticker, p);
  return p;
}
