/* ═══════════════════════════════════════════════════════════════════════
   store.js — the only module that knows where data comes from.

   Shape on disk (all static, generated by sp500_cache.py):
     data/index.json          one row per constituent, both snapshots
     data/summary.json        counts and failure reasons
     data/series/{TK}.json    EM history, per-day paths, daily OHLC bars

   The index loads once (~100 KB gzipped). Series load lazily on selection
   (~6 KB gzipped each) and are cached for the session, so revisiting a
   ticker is instant and a cold visit never pays for 498 of them.
   ═══════════════════════════════════════════════════════════════════════ */

const DATA = "./data";

const listeners = new Set();
const seriesCache = new Map();
const inflight = new Map();

export const state = {
  index: [],
  byTicker: new Map(),
  summary: null,
  selected: null,     // the row from index.json
  series: null,       // series for `selected`, or null while loading / absent
  seriesStatus: "idle", // idle | loading | ready | missing
  // indices into series.dates — which day the rating is read at, and which
  // earlier day it is measured against. Both are the reader's to choose.
  asOf: -1,
  compareAt: -1,
};

/** how far back the comparison starts, in trading days (≈ six months) */
const COMPARE_BACK = 125;

/**
 * The full model output for one trading day, in the same shape as the rows in
 * index.json — so every view can consume either without a special case.
 * `asset`, `marketCap` and the paths live in top-level arrays; everything the
 * rating chain produces lives in `path`.
 */
export function snapshotAt(series, i) {
  if (!series?.dates?.length) return null;
  const k = Math.max(0, Math.min(series.dates.length - 1, i));
  const p = series.path ?? {};
  const at = (key) => (Array.isArray(p[key]) ? p[key][k] : undefined);
  return {
    date: series.dates[k],
    index: k,
    asset: series.asset?.[k],
    marketCap: series.equity?.[k],
    debt: series.debt?.[k],
    price: at("price"),
    mu: at("mu"), ccm: at("ccm"), rs: at("rs"), fpPd: at("fpPd"),
    alpha: at("alpha"), spCcm: at("spCcm"), spPd: at("spPd"),
    spRating: at("spRating"), dd: at("dd"), edf: at("edf"),
    outlook: at("outlook"),
  };
}

/** the pair the views read: [as-of, comparison]. Falls back to the index row
 *  while the series is still in flight, so nothing waits on the network. */
export function snapshots() {
  const { series, selected, asOf, compareAt } = state;
  if (series?.path && asOf >= 0) {
    return [snapshotAt(series, asOf), compareAt >= 0 ? snapshotAt(series, compareAt) : null];
  }
  return selected?.snaps ? [selected.snaps[0], selected.snaps[1] ?? null] : [null, null];
}

/** the cached per-ticker series, fetched once and shared by every view */
export const seriesOf = (ticker) => fetchSeries(ticker);

/** index of the last day at or before `iso`, or null when the series starts later */
export function indexOfDate(series, iso) {
  const dates = series?.dates;
  if (!dates?.length || !iso) return null;
  for (let i = dates.length - 1; i >= 0; i -= 1) if (dates[i] <= iso) return i;
  return null;
}

/**
 * The peer cohort evaluated at two calendar dates rather than at the two dates
 * the build happened to freeze. Series are fetched once and cached, so dragging
 * a date redraws from memory. Peers whose history starts after the requested
 * day are dropped rather than drawn at the wrong date.
 */
export async function peerSnapshots(cohort, isoA, isoB) {
  const loaded = await Promise.all(
    cohort.map((row) => fetchSeries(row.ticker).then((s) => [row, s]).catch(() => [row, null]))
  );
  const out = [];
  for (const [row, series] of loaded) {
    if (!series?.path) continue;
    const ia = indexOfDate(series, isoA);
    const ib = indexOfDate(series, isoB);
    if (ia === null) continue;
    out.push({
      ticker: row.ticker,
      name: row.name,
      snaps: [snapshotAt(series, ia), ib === null ? null : snapshotAt(series, ib)],
    });
  }
  return out;
}

export function setAsOf(i) {
  const n = state.series?.dates?.length ?? 0;
  if (!n) return;
  const next = Math.max(0, Math.min(n - 1, Math.round(i)));
  if (next === state.asOf) return;
  state.asOf = next;
  // the comparison can never sit at or after the as-of date
  if (state.compareAt >= next) state.compareAt = Math.max(0, next - 1);
  emit("dates");
}

export function setCompareAt(i) {
  const n = state.series?.dates?.length ?? 0;
  if (!n) return;
  const next = Math.max(0, Math.min(state.asOf - 1 < 0 ? 0 : state.asOf - 1, Math.round(i)));
  if (next === state.compareAt) return;
  state.compareAt = next;
  emit("dates");
}

/** subscribe to state changes; returns an unsubscribe function */
export function subscribe(fn) {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

function emit(reason) {
  for (const fn of listeners) fn(state, reason);
}

export async function load() {
  const [index, summary] = await Promise.all([
    fetch(`${DATA}/index.json`).then((r) => {
      if (!r.ok) throw new Error(`index.json → HTTP ${r.status}`);
      return r.json();
    }),
    fetch(`${DATA}/summary.json`).then((r) => (r.ok ? r.json() : null)),
  ]);

  state.index = index;
  state.summary = summary;
  state.byTicker = new Map(index.map((row) => [row.ticker, row]));
  emit("index");
  return state;
}

export const rated = () => state.index.filter((r) => Array.isArray(r.snaps));
export const unrateable = () => state.index.filter((r) => !Array.isArray(r.snaps));

/** the largest names by market value — a data-driven "common stocks" row */
export function largest(n = 12) {
  return rated()
    .slice()
    .sort((a, b) => (b.snaps[0].marketCap ?? 0) - (a.snaps[0].marketCap ?? 0))
    .slice(0, n);
}

/**
 * A peer set for the cross-sectional plates: same GICS sector, the names
 * closest in market value, always including the subject itself.
 *
 * Drawing all 498 constituents in a dumbbell chart is unreadable, and picking
 * the largest 12 index-wide would compare a utility against Apple. Sector plus
 * size is the comparison a credit reader actually wants.
 */
export function peers(row, n = 12) {
  if (!row?.snaps) return [];
  const cohort = rated().filter((r) => r.sector === row.sector);
  const size = row.snaps[0].marketCap ?? 0;
  const near = cohort
    .filter((r) => r.ticker !== row.ticker)
    .sort((a, b) => Math.abs((a.snaps[0].marketCap ?? 0) - size) - Math.abs((b.snaps[0].marketCap ?? 0) - size))
    .slice(0, n - 1);
  return [row, ...near];
}

/**
 * Free-text lookup over symbol and company name. Exact symbol wins, then
 * symbol prefix, then name substring — so typing "KO" never buries Coca-Cola
 * under "Kohl's" or any name containing "ko".
 */
export function search(query, limit = 8) {
  const q = String(query ?? "").trim().toUpperCase();
  if (!q) return [];
  const exact = [];
  const prefix = [];
  const inName = [];
  for (const row of state.index) {
    const tk = row.ticker.toUpperCase();
    if (tk === q) exact.push(row);
    else if (tk.startsWith(q)) prefix.push(row);
    else if (String(row.name ?? "").toUpperCase().includes(q)) inName.push(row);
  }
  return [...exact, ...prefix, ...inName].slice(0, limit);
}

export async function select(ticker) {
  const row = state.byTicker.get(String(ticker ?? "").trim().toUpperCase());
  if (!row) return null;

  state.selected = row;
  state.series = seriesCache.get(row.ticker) ?? null;
  state.seriesStatus = state.series ? "ready" : row.snaps ? "loading" : "missing";
  resetDates();
  emit("selected");

  if (state.series || !row.snaps) return row;

  try {
    const series = await fetchSeries(row.ticker);
    seriesCache.set(row.ticker, series);
    // a later selection may have won the race — only publish if still current
    if (state.selected?.ticker === row.ticker) {
      state.series = series;
      state.seriesStatus = "ready";
      resetDates();
      emit("series");
    }
  } catch {
    if (state.selected?.ticker === row.ticker) {
      state.series = null;
      state.seriesStatus = "missing";
      emit("series");
    }
  }
  return row;
}

/** newest day as-of, ~six months back for the comparison */
function resetDates() {
  const n = state.series?.dates?.length ?? 0;
  state.asOf = n ? n - 1 : -1;
  state.compareAt = n ? Math.max(0, n - 1 - COMPARE_BACK) : -1;
}

function fetchSeries(ticker) {
  if (seriesCache.has(ticker)) return Promise.resolve(seriesCache.get(ticker));
  if (inflight.has(ticker)) return inflight.get(ticker);
  const p = fetch(`${DATA}/series/${encodeURIComponent(ticker)}.json`)
    .then((r) => {
      if (!r.ok) throw new Error(`series/${ticker} → HTTP ${r.status}`);
      return r.json();
    })
    .then((series) => {
      seriesCache.set(ticker, series);   // peers reuse this, so dragging a date is free
      return series;
    })
    .finally(() => inflight.delete(ticker));
  inflight.set(ticker, p);
  return p;
}
